### ISSUE TITLE
Expose the crate directory

### ISSUE THREAD

**Issue by kellpossible** [taiki-e/find-crate#15]
It would be nice for users of the library to also make use of the crate's directory resolution logic for their own purposes

**Comment by taiki-e** [comment]
Do you mean exposing this function? (It's basically just calling `env::var_os("CARGO_MANIFEST_DIR")`)

https://github.com/taiki-e/find-crate/blob/b17af1344dd22ff1140e26c93ab08aef9286ced9/src/lib.rs#L364-L371

**Comment by kellpossible** [comment]
Yes, but to know how this library chooses to locate the manifest a person needs to reverse engineer that. If someone's doing something with the manifest, there's a good chance they'll want the path to it too. It's not a big deal if you decide not to include this.

**Comment by taiki-e** [comment]
> to know how this library chooses to locate the manifest a person needs to reverse engineer that.

The way this library locates the manifest is documented and I don't think you need to read the source code. But we may need to improve the documentation.

Readme and crate-level documentation have the following description:

> `find_crate` and `Manifest::new` read `Cargo.toml` in `CARGO_MANIFEST_DIR` as manifest.

And [`find_crate`](https://docs.rs/find-crate/0.6.3/find_crate/fn.find_crate.html) and [`Manifest::new`](https://docs.rs/find-crate/0.6.3/find_crate/struct.Manifest.html#method.new) have the following description:

> This function reads `Cargo.toml` in `CARGO_MANIFEST_DIR` as manifest.

**Comment by kellpossible** [comment]
Cool, no worries then, we can close this. It's documented as an issue at least so it will be easy for someone to find if they want the information
